### ISSUE TITLE
"de_fc_ecdf" function 

### ISSUE THREAD

**Issue by LiZhengTai2022** [tacazares/SeedMatchR#4]
Hello developers, 
Following the tutorial you provided, I received a message that the "de_fc_ecdf" function is not available when I tried to execute this step. I installed the R package from CRAN. I would like to know whether the "de_fc_ecdf" function is no longer available in the new version, or has it been integrated into another feature? 
Thanks

**Comment by LiZhengTai2022** [comment]
I've found that it has been changed to "deseq_fc_ecdf".

**Comment by tacazares** [comment]
Sorry for the confusion! During publication we were given feedback that resulted in us changing the function from `deseq_fc_ecdf` to `de_fc_ecdf`. 

It looks like the version uploaded to CRAN did not have these updates. I will look into it more! For now, you can use the github version if you want updated functions. The webpage tutorials for the github repo are here: https://tacazares.github.io/SeedMatchR/
